[wallpaper]
enabled = true
fill_mode = "crop"
directory = "/home/gaybe/extras/wallpapers/horizontal/forest"
per_monitor_directories = true
transition = ["fade", "wipe", "disc", "stripes", "zoom", "honeycomb"]
transition_on_startup = true

[wallpaper.automation]
enabled = true
interval_seconds = 1200
order = "random"
recursive = true

[wallpaper.monitor.DP-2]
enabled = true
directory = "/home/gaybe/extras/wallpapers/vertical/forest"



[theme]
mode = "dark"
source = "builtin"
builtin = "Kanagawa"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = [
  "alacritty",
  "btop",
  "cava",
  "gtk3",
  "gtk4",
  "ghostty",
  "helix",
  "hyprland",
  "kcolorscheme",
  "kitty",
  "qt"
]
community_ids = [
  "discord",
  "libreoffice",
  "yazi"
]

