[bar]
order = [ "main" , "second" ]

[widget.workspaces]
label_source = "name"

[widget.lock_keys]
hide_when_off = true

[widget.network]
show_label = false

[widget.spacer]
length = 32

[widget.cpu]
visualization = "graph"

[widget.network_tx]
visualization = "graph"

[widget.network_rx]
visualization = "graph"

[widget.clock]
color = "primary"
font_weight = 700

[widget.date]
color = "primary"
font_weight = 700

[bar.main]
radius = 0.0
margin_ends = 0.0
widget_spacing = 15

start = [
  "workspaces",
  "spacer",
  "notifications",
  "clipboard",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "media",
]

center = [
  "date",
  "spacer",
  "clock",
  "lock_keys",
]

end    = [
  "tray",
  "cpu",
  "temp",
  "ram",
  "network_tx",
  "network_rx",
  "power_profile",
  "session"
]


[bar.main.dead_zone.actions]
left = "panel-toggle control-center"
right = "panel-toggle session"
middle = "settings-toggle"
scroll_up = "volume-up"
scroll_down = "volume-down"
back = "media previous"
forward = "media next"

[bar.main.monitor.dp2]
match = "DP-2"
enabled = false

[bar.second]
radius = 0.0
margin_ends = 0.0
widget_spacing = 15

start = [
  "date",
  "clock",
  "volume",
  "brightness",
  "battery",
  "media",
]

center = [
]

end    = [
  "cpu",
  "temp",
  "ram",
  "network_tx",
  "network_rx",
  "power_profile",
  "session"
]

[bar.second.dead_zone.actions]
left = "panel-toggle control-center"
right = "panel-toggle session"
middle = "settings-toggle"
scroll_up = "volume-up"
scroll_down = "volume-down"
back = "media previous"
forward = "media next"

[bar.second.monitor.dp1]
match = "DP-1"
enabled = false
