
[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-001",
    "desktop-widget-002",
    "desktop-widget-003",
    "desktop-widget-004",
    "desktop-widget-006",
    "desktop-widget-007",
    "desktop-widget-008",
    "desktop-widget-009",
    "desktop-widget-00a"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-009]
    box_height = 512.0
    box_width = 1120.0
    cx = 256
    cy = 552.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 1.5707963705062866
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-009.settings]
        background = false
        bands = 92
        centered = false
        mirrored = false
        reversed = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-00a]
    box_height = 512.0
    box_width = 1120.0
    cx = 2304.0
    cy = 552.0
    flip_x = true
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = -1.5707963705062866
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-00a.settings]
        background = false
        bands = 112
        centered = false
        mirrored = false
        reversed = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-001]
    box_height = 544.0
    box_width = 2544.0
    cx = 1280.0
    cy = 1168.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-001.settings]
        background = false
        bands = 128
        centered = false
        fade_when_idle = true
        reversed = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-002]
    box_height = 752.0
    box_width = 800.0
    cx = 1280.0
    cy = 600.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 1.5707963
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-002.settings]
        background = false
        bar_width = 0.4
        bloom_intensity = 0.35
        fade_when_idle = true
        inner_diameter = 0.6
        rotation_speed = 0.0
        visualization_mode = "all"
        wave_thickness = 0.6

    [desktop_widgets.widget.desktop-widget-003]
    box_height = 240.0
    box_width = 512.0
    cx = 268.0
    cy = 1472.0
    output = "DP-2"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = -0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-003.settings]
        background = false
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-004]
    box_height = 240.0
    box_width = 512.0
    cx = 812.0
    cy = 1472.0
    output = "DP-2"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-004.settings]
        background = false
        stat = "gpu_usage"
        stat2 = "gpu_temp"

    [desktop_widgets.widget.desktop-widget-006]
    box_height = 240.0
    box_width = 512.0
    cx = 268.0
    cy = 1768.0
    output = "DP-2"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-006.settings]
        background = false
        display = "graph"
        stat = "ram_pct"
        stat2 = "gpu_vram"

    [desktop_widgets.widget.desktop-widget-007]
    box_height = 240.0
    box_width = 512.0
    cx = 812.0
    cy = 1768.0
    output = "DP-2"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-007.settings]
        background = false
        stat = "net_rx"
        stat2 = "net_tx"

    [desktop_widgets.widget.desktop-widget-008]
    box_height = 384.0
    box_width = 528.0
    cx = 540.0
    cy = 576.0
    output = "DP-2"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-008.settings]
        background = false
        clock_style = "digital"

